// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoCrud.Context;

#nullable disable

namespace ProjetoCrud.Migrations
{
    [DbContext(typeof(FilmesContext))]
    [Migration("20240620193702_CrudFilmes")]
    partial class CrudFilmes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoCrud.Domains.Filme", b =>
                {
                    b.Property<Guid>("IdFilme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("DATE");

                    b.Property<string>("FilmeDescription")
                        .HasColumnType("VARCHAR(300)");

                    b.Property<string>("Gênero")
                        .HasColumnType("VARCHAR(300)");

                    b.Property<string>("NomeFilme")
                        .HasColumnType("VARCHAR(300)");

                    b.HasKey("IdFilme");

                    b.ToTable("Filme");
                });
#pragma warning restore 612, 618
        }
    }
}
